CREATE USER IF NOT EXISTS `${DB_USER}`@'%' IDENTIFIED BY '${DB_PASSWORD}';
GRANT CREATE ON *.* TO `${DB_USER}`@'%';
GRANT ALL PRIVILEGES ON `${DB_NAME}`.* TO `${DB_USER}`@'%';
GRANT CREATE, ALTER, DROP, REFERENCES ON *.* TO `${DB_USER}`@'%';
FLUSH PRIVILEGES;
USE `${DB_USER}`;
CREATE DATABASE IF NOT EXISTS `${DB_NAME}`;
SHOW TABLES;